### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by bd0bd** [backdrop-contrib/block_refresh#1]
The info file (temporary://update-extraction-03a5c401/block_refresh-1.x-2.x/tests/block_refresh.tests.info) does not define a 'type' attribute.

Steps to reproduce:
* attempt install this module using project browser

**Comment by bd0bd** [comment]
![img_20170517_020937](https://cloud.githubusercontent.com/assets/13515302/26132005/0385d8d4-3aa6-11e7-87d1-bafa5ba04c2e.JPG)

**Comment by jenlampton** [comment]
Wow, thanks @bd0bd, you are fast with the testing! This is a very strange error. That file is a tests file, so it does not need a type attribute. I wonder why Backdrop thinks it is a module .info file... 

Are you on Backdrop 1.7?  Do you see this error with any other modules (that have tests) or only for this one?

**Comment by bd0bd** [comment]
1.6.3

Sorry, I do not know about  "test" modules (what is it).
I do not have any problems with installing other modules.

**Comment by jenlampton** [comment]
Thanks for the reply.  I wonder if you will have the same problem with an official release. Can you try to install [this version](https://backdropcms.org/project/block_refresh) through the project browser and see if it behaves the same way?

**Comment by bd0bd** [comment]
Successfully installed.
BD 1.6.3

**Comment by bd0bd** [comment]
But I do not see any link to refresh the block.

May be I do not clear understand what this module is for.

I was expecting to place different content in the block and it should be displayed after a visitor click the NEXT link (prev .... next  .... last).

**Comment by jenlampton** [comment]
In my example, I have a block that displays the current song playing on the radio. The radio plays different songs all the time, so I need that block to refresh itself frequently. Adding this module allows me to have that block refresh by itself.

**Comment by jenlampton** [comment]
There is a manual refresh setting for the block too. What that would do is allow anyone looking at the block to reload the block's contents by clicking a 'Refresh' link. There wouldn't be a prev .... next .... last because there is only one.

**Comment by bd0bd** [comment]
Hm, why to reload/refresh it to show  the same content?
My idea was it will show ANOTHER content.
For example we have 2 content within one block - by default we see content #1 and  after refreshing we see content #2.

I do not have the 'Refresh' link. But I have set up it in the block setting.

**Comment by jenlampton** [comment]
> Hm, why to reload/refresh it to show the same content?

Because that's what this module is designed to do. Every block only has one content, and this module refreshes a block's content.  

The feature you are describing can be accomplished with Views.

**Comment by bd0bd** [comment]
No any link  in my block.
But I have done the necessary settings:

![img_20170518_022137](https://cloud.githubusercontent.com/assets/13515302/26180211/cb2b8f3a-3b70-11e7-8436-66b7b9caadec.JPG)

**Comment by klonos** [comment]
The original problem reported here (missing project type) has been solved. So I will go ahead and close this issue. Please refer to #2 for the issue you've reported @bd0bd
